# Welcome to the sample config file
# Below you will find various config sections and options
# Default values are shown

# The string to prefix messages with to talk to the bot in group chats
command_prefix: "!middleman"

# Options for connecting to the bot's Matrix account
matrix:
  # The Matrix User ID of the bot account
  user_id: "@bot:example.com"
  # Matrix account password (optional if access token used)
  user_password: ""
  # Matrix account access token (optional if password used)
  #user_token: ""
  # The URL of the homeserver to connect to
  homeserver_url: https://example.com
  # The device ID that is **non pre-existing** device
  # If this device ID already exists, messages will be dropped silently in encrypted rooms
  device_id: ABCDEFGHIJ
  # What to name the logged in device
  device_name: middleman-bot

middleman:
  # Management room where proxied messages are sent and where actions are taken.
  # Can be an alias or room ID. Middleman must be able to join it on startup.
  management_room: "!1234567:example.com"
  # Anonymous senders
  # If set to true, relayed messages to management room will not contain
  # any sender information.
  anonymise_senders: false
  # Welcome message which is sent to anyone inviting Middleman to a room.
  # Comment out to disable sending any message.
  welcome_message: |
    Hello! I'm Middleman, a bot. I will relay your message forward to the maintainers of this
    bot. When they reply, you will see the message here. Ps. Sorry, images are not currently
    supported, text only please!
  # List of rooms to only relay messages from when explicitly mentioned
  # Any rooms here (alias or ID) will have messages relayed to the management
  # room only if the bot is mentioned in the message. This allows joining the bot
  # to rooms with a large amount of messages for support needs, for example.
  mention_only_rooms: []

storage:
  # The database connection string
  # For SQLite3, this would look like:
  #     database: "sqlite://bot.db"
  # For Postgres, this would look like:
  #     database: "postgres://username:password@localhost/dbname?sslmode=disable"
  database: "sqlite://bot.db"
  # The path to a directory for internal bot storage
  # containing encryption keys, sync tokens, etc.
  store_path: "./store"

# Logging setup
logging:
  # Logging level
  # Allowed levels are 'INFO', 'WARNING', 'ERROR', 'DEBUG' where DEBUG is most verbose
  level: INFO
  # Configure logging to a file
  file_logging:
    # Whether logging to a file is enabled
    enabled: false
    # The path to the file to log to. May be relative or absolute
    filepath: bot.log
  # Configure logging to the console output
  console_logging:
    # Whether logging to the console is enabled
    enabled: true
